#!/bin/bash

# Comandos curl directos para copiar y pegar
# Ajustar las variables según tu entorno

WSO2_URL="https://localhost:8243"
BPM_SESSION="your_bpm_session_token_here"
EMAIL="test$(date +%s)@example.com"
USERNAME="testuser$(date +%s)"

echo "=== Comandos curl para probar API Usuario ==="
echo ""
echo "# 1. Crear usuario"
echo "curl -X POST \"${WSO2_URL}/tools/core/usuario\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -d '{"
echo "    \"bpmSession\": \"${BPM_SESSION}\","
echo "    \"usuario\": {"
echo "      \"firstname\": \"Test\","
echo "      \"lastname\": \"User\","
echo "      \"email\": \"${EMAIL}\","
echo "      \"password\": \"Test123456\","
echo "      \"role\": \"subscriber\","
echo "      \"status\": \"active\","
echo "      \"banned_users\": \"\","
echo "      \"telefono\": \"+5491112345678\","
echo "      \"dni\": \"12345678\","
echo "      \"usernick\": \"${USERNAME}\","
echo "      \"depo_id\": null,"
echo "      \"image_name\": null,"
echo "      \"image\": null,"
echo "      \"business\": \"empresa_test\""
echo "    }"
echo "  }'"
echo ""
echo ""
echo "# 2. Verificar duplicado (Data Service directo)"
echo "curl -X GET \"${WSO2_URL}/services/COREDataService/usuario/duplicado/${EMAIL}\" \\"
echo "  -H \"Accept: application/json\""
echo ""
echo ""
echo "# 3. Crear usuario usando archivo JSON"
echo "curl -X POST \"${WSO2_URL}/tools/core/usuario\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -d @payload_example.json"
echo ""
echo ""
echo "# 4. Crear usuario Admin"
echo "curl -X POST \"${WSO2_URL}/tools/core/usuario\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -d '{"
echo "    \"bpmSession\": \"${BPM_SESSION}\","
echo "    \"usuario\": {"
echo "      \"firstname\": \"Admin\","
echo "      \"lastname\": \"User\","
echo "      \"email\": \"admin$(date +%s)@example.com\","
echo "      \"password\": \"Admin123456\","
echo "      \"role\": \"admin\","
echo "      \"status\": \"active\","
echo "      \"banned_users\": \"\","
echo "      \"telefono\": \"+5491112345678\","
echo "      \"dni\": \"87654321\","
echo "      \"usernick\": \"admin$(date +%s)\","
echo "      \"depo_id\": null,"
echo "      \"image_name\": null,"
echo "      \"image\": null,"
echo "      \"business\": \"empresa_test\""
echo "    }"
echo "  }'"
echo ""

