---
key: "ProduccionDataService_proxy-1.0.0"
name: "ProduccionDataService"
displayName: "ProduccionDataService"
version: "1.0.0"
serviceUrl: "https://{MI_HOST}:{MI_PORT}/services/ProduccionDataService"
definitionType: "OAS3"
securityType: "BASIC"
mutualSSLEnabled: false
