---
key: "PRODataService_proxy-1.0.0"
name: "PRODataService"
displayName: "PRODataService"
version: "1.0.0"
serviceUrl: "https://{MI_HOST}:{MI_PORT}/services/PRODataService"
definitionType: "OAS3"
securityType: "BASIC"
mutualSSLEnabled: false
